package omok.domain.judgment

import omok.domain.board.Column
import omok.domain.board.Position
import omok.domain.board.Row
import omok.domain.player.Black
import omok.domain.player.Stone
import omok.domain.player.White

val THREE_THREE_BOARD: MutableMap<Position, Stone?> = mutableMapOf(
    Position(Column.A, Row.FIFTEEN) to null, Position(Column.B, Row.FIFTEEN) to null, Position(Column.C, Row.FIFTEEN) to null, Position(Column.D, Row.FIFTEEN) to null, Position(Column.E, Row.FIFTEEN) to null, Position(Column.F, Row.FIFTEEN) to null, Position(Column.G, Row.FIFTEEN) to null, Position(Column.H, Row.FIFTEEN) to null, Position(Column.I, Row.FIFTEEN) to null, Position(Column.J, Row.FIFTEEN) to null, Position(Column.K, Row.FIFTEEN) to null, Position(Column.L, Row.FIFTEEN) to null, Position(Column.M, Row.FIFTEEN) to null, Position(Column.N, Row.FIFTEEN) to null, Position(Column.O, Row.FIFTEEN) to null,
    Position(Column.A, Row.FOURTEEN) to null, Position(Column.B, Row.FOURTEEN) to null, Position(Column.C, Row.FOURTEEN) to null, Position(Column.D, Row.FOURTEEN) to Black, Position(Column.E, Row.FOURTEEN) to null, Position(Column.F, Row.FOURTEEN) to null, Position(Column.G, Row.FOURTEEN) to null, Position(Column.H, Row.FOURTEEN) to null, Position(Column.I, Row.FOURTEEN) to null, Position(Column.J, Row.FOURTEEN) to null, Position(Column.K, Row.FOURTEEN) to null, Position(Column.L, Row.FOURTEEN) to null, Position(Column.M, Row.FOURTEEN) to null, Position(Column.N, Row.FOURTEEN) to null, Position(Column.O, Row.FOURTEEN) to null,
    Position(Column.A, Row.THIRTEEN) to null, Position(Column.B, Row.THIRTEEN) to null, Position(Column.C, Row.THIRTEEN) to null, Position(Column.D, Row.THIRTEEN) to Black, Position(Column.E, Row.THIRTEEN) to null, Position(Column.F, Row.THIRTEEN) to null, Position(Column.G, Row.THIRTEEN) to null, Position(Column.H, Row.THIRTEEN) to null, Position(Column.I, Row.THIRTEEN) to null, Position(Column.J, Row.THIRTEEN) to null, Position(Column.K, Row.THIRTEEN) to null, Position(Column.L, Row.THIRTEEN) to null, Position(Column.M, Row.THIRTEEN) to null, Position(Column.N, Row.THIRTEEN) to null, Position(Column.O, Row.THIRTEEN) to null,
    Position(Column.A, Row.TWELVE) to null, Position(Column.B, Row.TWELVE) to null, Position(Column.C, Row.TWELVE) to Black, Position(Column.D, Row.TWELVE) to null, Position(Column.E, Row.TWELVE) to Black, Position(Column.F, Row.TWELVE) to null, Position(Column.G, Row.TWELVE) to null, Position(Column.H, Row.TWELVE) to null, Position(Column.I, Row.TWELVE) to null, Position(Column.J, Row.TWELVE) to null, Position(Column.K, Row.TWELVE) to null, Position(Column.L, Row.TWELVE) to null, Position(Column.M, Row.TWELVE) to Black, Position(Column.N, Row.TWELVE) to null, Position(Column.O, Row.TWELVE) to null,
    Position(Column.A, Row.ELEVEN) to null, Position(Column.B, Row.ELEVEN) to null, Position(Column.C, Row.ELEVEN) to null, Position(Column.D, Row.ELEVEN) to null, Position(Column.E, Row.ELEVEN) to null, Position(Column.F, Row.ELEVEN) to null, Position(Column.G, Row.ELEVEN) to null, Position(Column.H, Row.ELEVEN) to null, Position(Column.I, Row.ELEVEN) to null, Position(Column.J, Row.ELEVEN) to null, Position(Column.K, Row.ELEVEN) to null, Position(Column.L, Row.ELEVEN) to null, Position(Column.M, Row.ELEVEN) to null, Position(Column.N, Row.ELEVEN) to null, Position(Column.O, Row.ELEVEN) to null,
    Position(Column.A, Row.TEN) to null, Position(Column.B, Row.TEN) to null, Position(Column.C, Row.TEN) to null, Position(Column.D, Row.TEN) to null, Position(Column.E, Row.TEN) to null, Position(Column.F, Row.TEN) to null, Position(Column.G, Row.TEN) to null, Position(Column.H, Row.TEN) to null, Position(Column.I, Row.TEN) to null, Position(Column.J, Row.TEN) to null, Position(Column.K, Row.TEN) to null, Position(Column.L, Row.TEN) to null, Position(Column.M, Row.TEN) to Black, Position(Column.N, Row.TEN) to null, Position(Column.O, Row.TEN) to null,
    Position(Column.A, Row.NINE) to null, Position(Column.B, Row.NINE) to null, Position(Column.C, Row.NINE) to null, Position(Column.D, Row.NINE) to null, Position(Column.E, Row.NINE) to null, Position(Column.F, Row.NINE) to null, Position(Column.G, Row.NINE) to null, Position(Column.H, Row.NINE) to null, Position(Column.I, Row.NINE) to null, Position(Column.J, Row.NINE) to Black, Position(Column.K, Row.NINE) to null, Position(Column.L, Row.NINE) to null, Position(Column.M, Row.NINE) to null, Position(Column.N, Row.NINE) to Black, Position(Column.O, Row.NINE) to null,
    Position(Column.A, Row.EIGHT) to null, Position(Column.B, Row.EIGHT) to null, Position(Column.C, Row.EIGHT) to null, Position(Column.D, Row.EIGHT) to null, Position(Column.E, Row.EIGHT) to null, Position(Column.F, Row.EIGHT) to null, Position(Column.G, Row.EIGHT) to null, Position(Column.H, Row.EIGHT) to null, Position(Column.I, Row.EIGHT) to null, Position(Column.J, Row.EIGHT) to null, Position(Column.K, Row.EIGHT) to null, Position(Column.L, Row.EIGHT) to null, Position(Column.M, Row.EIGHT) to null, Position(Column.N, Row.EIGHT) to null, Position(Column.O, Row.EIGHT) to null,
    Position(Column.A, Row.SEVEN) to null, Position(Column.B, Row.SEVEN) to null, Position(Column.C, Row.SEVEN) to null, Position(Column.D, Row.SEVEN) to null, Position(Column.E, Row.SEVEN) to null, Position(Column.F, Row.SEVEN) to null, Position(Column.G, Row.SEVEN) to null, Position(Column.H, Row.SEVEN) to null, Position(Column.I, Row.SEVEN) to null, Position(Column.J, Row.SEVEN) to null, Position(Column.K, Row.SEVEN) to null, Position(Column.L, Row.SEVEN) to null, Position(Column.M, Row.SEVEN) to null, Position(Column.N, Row.SEVEN) to null, Position(Column.O, Row.SEVEN) to null,
    Position(Column.A, Row.SIX) to null, Position(Column.B, Row.SIX) to Black, Position(Column.C, Row.SIX) to null, Position(Column.D, Row.SIX) to null, Position(Column.E, Row.SIX) to Black, Position(Column.F, Row.SIX) to null, Position(Column.G, Row.SIX) to null, Position(Column.H, Row.SIX) to null, Position(Column.I, Row.SIX) to null, Position(Column.J, Row.SIX) to null, Position(Column.K, Row.SIX) to Black, Position(Column.L, Row.SIX) to null, Position(Column.M, Row.SIX) to null, Position(Column.N, Row.SIX) to null, Position(Column.O, Row.SIX) to null,
    Position(Column.A, Row.FIVE) to null, Position(Column.B, Row.FIVE) to null, Position(Column.C, Row.FIVE) to Black, Position(Column.D, Row.FIVE) to null, Position(Column.E, Row.FIVE) to Black, Position(Column.F, Row.FIVE) to null, Position(Column.G, Row.FIVE) to null, Position(Column.H, Row.FIVE) to null, Position(Column.I, Row.FIVE) to null, Position(Column.J, Row.FIVE) to null, Position(Column.K, Row.FIVE) to null, Position(Column.L, Row.FIVE) to null, Position(Column.M, Row.FIVE) to null, Position(Column.N, Row.FIVE) to null, Position(Column.O, Row.FIVE) to null,
    Position(Column.A, Row.FOUR) to null, Position(Column.B, Row.FOUR) to null, Position(Column.C, Row.FOUR) to null, Position(Column.D, Row.FOUR) to null, Position(Column.E, Row.FOUR) to null, Position(Column.F, Row.FOUR) to null, Position(Column.G, Row.FOUR) to null, Position(Column.H, Row.FOUR) to null, Position(Column.I, Row.FOUR) to null, Position(Column.J, Row.FOUR) to null, Position(Column.K, Row.FOUR) to null, Position(Column.L, Row.FOUR) to null, Position(Column.M, Row.FOUR) to Black, Position(Column.N, Row.FOUR) to Black, Position(Column.O, Row.FOUR) to null,
    Position(Column.A, Row.THREE) to null, Position(Column.B, Row.THREE) to null, Position(Column.C, Row.THREE) to null, Position(Column.D, Row.THREE) to null, Position(Column.E, Row.THREE) to null, Position(Column.F, Row.THREE) to null, Position(Column.G, Row.THREE) to null, Position(Column.H, Row.THREE) to null, Position(Column.I, Row.THREE) to null, Position(Column.J, Row.THREE) to null, Position(Column.K, Row.THREE) to Black, Position(Column.L, Row.THREE) to null, Position(Column.M, Row.THREE) to null, Position(Column.N, Row.THREE) to null, Position(Column.O, Row.THREE) to null,
    Position(Column.A, Row.TWO) to null, Position(Column.B, Row.TWO) to null, Position(Column.C, Row.TWO) to null, Position(Column.D, Row.TWO) to null, Position(Column.E, Row.TWO) to null, Position(Column.F, Row.TWO) to null, Position(Column.G, Row.TWO) to null, Position(Column.H, Row.TWO) to null, Position(Column.I, Row.TWO) to null, Position(Column.J, Row.TWO) to null, Position(Column.K, Row.TWO) to null, Position(Column.L, Row.TWO) to null, Position(Column.M, Row.TWO) to null, Position(Column.N, Row.TWO) to null, Position(Column.O, Row.TWO) to null,
    Position(Column.A, Row.ONE) to null, Position(Column.B, Row.ONE) to null, Position(Column.C, Row.ONE) to null, Position(Column.D, Row.ONE) to null, Position(Column.E, Row.ONE) to null, Position(Column.F, Row.ONE) to null, Position(Column.G, Row.ONE) to null, Position(Column.H, Row.ONE) to null, Position(Column.I, Row.ONE) to null, Position(Column.J, Row.ONE) to null, Position(Column.K, Row.ONE) to null, Position(Column.L, Row.ONE) to null, Position(Column.M, Row.ONE) to null, Position(Column.N, Row.ONE) to null, Position(Column.O, Row.ONE) to null
)

val FOUR_THREE_BOARD: MutableMap<Position, Stone?> = mutableMapOf(
    Position(Column.A, Row.FIFTEEN) to null, Position(Column.B, Row.FIFTEEN) to null, Position(Column.C, Row.FIFTEEN) to null, Position(Column.D, Row.FIFTEEN) to null, Position(Column.E, Row.FIFTEEN) to null, Position(Column.F, Row.FIFTEEN) to null, Position(Column.G, Row.FIFTEEN) to null, Position(Column.H, Row.FIFTEEN) to null, Position(Column.I, Row.FIFTEEN) to null, Position(Column.J, Row.FIFTEEN) to null, Position(Column.K, Row.FIFTEEN) to null, Position(Column.L, Row.FIFTEEN) to null, Position(Column.M, Row.FIFTEEN) to null, Position(Column.N, Row.FIFTEEN) to null, Position(Column.O, Row.FIFTEEN) to null,
    Position(Column.A, Row.FOURTEEN) to null, Position(Column.B, Row.FOURTEEN) to null, Position(Column.C, Row.FOURTEEN) to null, Position(Column.D, Row.FOURTEEN) to Black, Position(Column.E, Row.FOURTEEN) to null, Position(Column.F, Row.FOURTEEN) to null, Position(Column.G, Row.FOURTEEN) to null, Position(Column.H, Row.FOURTEEN) to null, Position(Column.I, Row.FOURTEEN) to null, Position(Column.J, Row.FOURTEEN) to null, Position(Column.K, Row.FOURTEEN) to null, Position(Column.L, Row.FOURTEEN) to null, Position(Column.M, Row.FOURTEEN) to null, Position(Column.N, Row.FOURTEEN) to null, Position(Column.O, Row.FOURTEEN) to null,
    Position(Column.A, Row.THIRTEEN) to null, Position(Column.B, Row.THIRTEEN) to null, Position(Column.C, Row.THIRTEEN) to null, Position(Column.D, Row.THIRTEEN) to Black, Position(Column.E, Row.THIRTEEN) to null, Position(Column.F, Row.THIRTEEN) to null, Position(Column.G, Row.THIRTEEN) to null, Position(Column.H, Row.THIRTEEN) to null, Position(Column.I, Row.THIRTEEN) to null, Position(Column.J, Row.THIRTEEN) to null, Position(Column.K, Row.THIRTEEN) to null, Position(Column.L, Row.THIRTEEN) to null, Position(Column.M, Row.THIRTEEN) to null, Position(Column.N, Row.THIRTEEN) to null, Position(Column.O, Row.THIRTEEN) to null,
    Position(Column.A, Row.TWELVE) to null, Position(Column.B, Row.TWELVE) to null, Position(Column.C, Row.TWELVE) to Black, Position(Column.D, Row.TWELVE) to null, Position(Column.E, Row.TWELVE) to Black, Position(Column.F, Row.TWELVE) to null, Position(Column.G, Row.TWELVE) to null, Position(Column.H, Row.TWELVE) to null, Position(Column.I, Row.TWELVE) to null, Position(Column.J, Row.TWELVE) to null, Position(Column.K, Row.TWELVE) to null, Position(Column.L, Row.TWELVE) to null, Position(Column.M, Row.TWELVE) to null, Position(Column.N, Row.TWELVE) to null, Position(Column.O, Row.TWELVE) to null,
    Position(Column.A, Row.ELEVEN) to null, Position(Column.B, Row.ELEVEN) to null, Position(Column.C, Row.ELEVEN) to null, Position(Column.D, Row.ELEVEN) to Black, Position(Column.E, Row.ELEVEN) to null, Position(Column.F, Row.ELEVEN) to null, Position(Column.G, Row.ELEVEN) to null, Position(Column.H, Row.ELEVEN) to null, Position(Column.I, Row.ELEVEN) to null, Position(Column.J, Row.ELEVEN) to null, Position(Column.K, Row.ELEVEN) to null, Position(Column.L, Row.ELEVEN) to null, Position(Column.M, Row.ELEVEN) to null, Position(Column.N, Row.ELEVEN) to null, Position(Column.O, Row.ELEVEN) to null,
    Position(Column.A, Row.TEN) to null, Position(Column.B, Row.TEN) to null, Position(Column.C, Row.TEN) to null, Position(Column.D, Row.TEN) to null, Position(Column.E, Row.TEN) to null, Position(Column.F, Row.TEN) to null, Position(Column.G, Row.TEN) to null, Position(Column.H, Row.TEN) to null, Position(Column.I, Row.TEN) to null, Position(Column.J, Row.TEN) to null, Position(Column.K, Row.TEN) to null, Position(Column.L, Row.TEN) to null, Position(Column.M, Row.TEN) to null, Position(Column.N, Row.TEN) to null, Position(Column.O, Row.TEN) to null,
    Position(Column.A, Row.NINE) to null, Position(Column.B, Row.NINE) to null, Position(Column.C, Row.NINE) to null, Position(Column.D, Row.NINE) to null, Position(Column.E, Row.NINE) to null, Position(Column.F, Row.NINE) to null, Position(Column.G, Row.NINE) to null, Position(Column.H, Row.NINE) to null, Position(Column.I, Row.NINE) to null, Position(Column.J, Row.NINE) to null, Position(Column.K, Row.NINE) to null, Position(Column.L, Row.NINE) to null, Position(Column.M, Row.NINE) to null, Position(Column.N, Row.NINE) to null, Position(Column.O, Row.NINE) to null,
    Position(Column.A, Row.EIGHT) to null, Position(Column.B, Row.EIGHT) to null, Position(Column.C, Row.EIGHT) to null, Position(Column.D, Row.EIGHT) to null, Position(Column.E, Row.EIGHT) to null, Position(Column.F, Row.EIGHT) to null, Position(Column.G, Row.EIGHT) to null, Position(Column.H, Row.EIGHT) to null, Position(Column.I, Row.EIGHT) to null, Position(Column.J, Row.EIGHT) to null, Position(Column.K, Row.EIGHT) to null, Position(Column.L, Row.EIGHT) to null, Position(Column.M, Row.EIGHT) to null, Position(Column.N, Row.EIGHT) to null, Position(Column.O, Row.EIGHT) to null,
    Position(Column.A, Row.SEVEN) to null, Position(Column.B, Row.SEVEN) to null, Position(Column.C, Row.SEVEN) to null, Position(Column.D, Row.SEVEN) to null, Position(Column.E, Row.SEVEN) to null, Position(Column.F, Row.SEVEN) to null, Position(Column.G, Row.SEVEN) to null, Position(Column.H, Row.SEVEN) to null, Position(Column.I, Row.SEVEN) to null, Position(Column.J, Row.SEVEN) to null, Position(Column.K, Row.SEVEN) to null, Position(Column.L, Row.SEVEN) to null, Position(Column.M, Row.SEVEN) to null, Position(Column.N, Row.SEVEN) to null, Position(Column.O, Row.SEVEN) to null,
    Position(Column.A, Row.SIX) to null, Position(Column.B, Row.SIX) to null, Position(Column.C, Row.SIX) to null, Position(Column.D, Row.SIX) to null, Position(Column.E, Row.SIX) to null, Position(Column.F, Row.SIX) to null, Position(Column.G, Row.SIX) to null, Position(Column.H, Row.SIX) to null, Position(Column.I, Row.SIX) to null, Position(Column.J, Row.SIX) to null, Position(Column.K, Row.SIX) to null, Position(Column.L, Row.SIX) to null, Position(Column.M, Row.SIX) to null, Position(Column.N, Row.SIX) to null, Position(Column.O, Row.SIX) to null,
    Position(Column.A, Row.FIVE) to null, Position(Column.B, Row.FIVE) to null, Position(Column.C, Row.FIVE) to null, Position(Column.D, Row.FIVE) to null, Position(Column.E, Row.FIVE) to null, Position(Column.F, Row.FIVE) to null, Position(Column.G, Row.FIVE) to null, Position(Column.H, Row.FIVE) to null, Position(Column.I, Row.FIVE) to null, Position(Column.J, Row.FIVE) to null, Position(Column.K, Row.FIVE) to null, Position(Column.L, Row.FIVE) to null, Position(Column.M, Row.FIVE) to null, Position(Column.N, Row.FIVE) to null, Position(Column.O, Row.FIVE) to null,
    Position(Column.A, Row.FOUR) to null, Position(Column.B, Row.FOUR) to null, Position(Column.C, Row.FOUR) to null, Position(Column.D, Row.FOUR) to null, Position(Column.E, Row.FOUR) to null, Position(Column.F, Row.FOUR) to null, Position(Column.G, Row.FOUR) to null, Position(Column.H, Row.FOUR) to null, Position(Column.I, Row.FOUR) to null, Position(Column.J, Row.FOUR) to null, Position(Column.K, Row.FOUR) to null, Position(Column.L, Row.FOUR) to null, Position(Column.M, Row.FOUR) to null, Position(Column.N, Row.FOUR) to null, Position(Column.O, Row.FOUR) to null,
    Position(Column.A, Row.THREE) to null, Position(Column.B, Row.THREE) to null, Position(Column.C, Row.THREE) to null, Position(Column.D, Row.THREE) to null, Position(Column.E, Row.THREE) to null, Position(Column.F, Row.THREE) to null, Position(Column.G, Row.THREE) to null, Position(Column.H, Row.THREE) to null, Position(Column.I, Row.THREE) to null, Position(Column.J, Row.THREE) to null, Position(Column.K, Row.THREE) to null, Position(Column.L, Row.THREE) to null, Position(Column.M, Row.THREE) to null, Position(Column.N, Row.THREE) to null, Position(Column.O, Row.THREE) to null,
    Position(Column.A, Row.TWO) to null, Position(Column.B, Row.TWO) to null, Position(Column.C, Row.TWO) to null, Position(Column.D, Row.TWO) to null, Position(Column.E, Row.TWO) to null, Position(Column.F, Row.TWO) to null, Position(Column.G, Row.TWO) to null, Position(Column.H, Row.TWO) to null, Position(Column.I, Row.TWO) to null, Position(Column.J, Row.TWO) to null, Position(Column.K, Row.TWO) to null, Position(Column.L, Row.TWO) to null, Position(Column.M, Row.TWO) to null, Position(Column.N, Row.TWO) to null, Position(Column.O, Row.TWO) to null,
    Position(Column.A, Row.ONE) to null, Position(Column.B, Row.ONE) to null, Position(Column.C, Row.ONE) to null, Position(Column.D, Row.ONE) to null, Position(Column.E, Row.ONE) to null, Position(Column.F, Row.ONE) to null, Position(Column.G, Row.ONE) to null, Position(Column.H, Row.ONE) to null, Position(Column.I, Row.ONE) to null, Position(Column.J, Row.ONE) to null, Position(Column.K, Row.ONE) to null, Position(Column.L, Row.ONE) to null, Position(Column.M, Row.ONE) to null, Position(Column.N, Row.ONE) to null, Position(Column.O, Row.ONE) to null
)

val FOUR_THREE_THREE_BOARD: MutableMap<Position, Stone?> = mutableMapOf(
    Position(Column.A, Row.FIFTEEN) to null, Position(Column.B, Row.FIFTEEN) to null, Position(Column.C, Row.FIFTEEN) to null, Position(Column.D, Row.FIFTEEN) to null, Position(Column.E, Row.FIFTEEN) to null, Position(Column.F, Row.FIFTEEN) to null, Position(Column.G, Row.FIFTEEN) to null, Position(Column.H, Row.FIFTEEN) to null, Position(Column.I, Row.FIFTEEN) to null, Position(Column.J, Row.FIFTEEN) to null, Position(Column.K, Row.FIFTEEN) to null, Position(Column.L, Row.FIFTEEN) to null, Position(Column.M, Row.FIFTEEN) to null, Position(Column.N, Row.FIFTEEN) to null, Position(Column.O, Row.FIFTEEN) to null,
    Position(Column.A, Row.FOURTEEN) to null, Position(Column.B, Row.FOURTEEN) to null, Position(Column.C, Row.FOURTEEN) to null, Position(Column.D, Row.FOURTEEN) to Black, Position(Column.E, Row.FOURTEEN) to null, Position(Column.F, Row.FOURTEEN) to null, Position(Column.G, Row.FOURTEEN) to null, Position(Column.H, Row.FOURTEEN) to null, Position(Column.I, Row.FOURTEEN) to null, Position(Column.J, Row.FOURTEEN) to null, Position(Column.K, Row.FOURTEEN) to null, Position(Column.L, Row.FOURTEEN) to null, Position(Column.M, Row.FOURTEEN) to null, Position(Column.N, Row.FOURTEEN) to null, Position(Column.O, Row.FOURTEEN) to null,
    Position(Column.A, Row.THIRTEEN) to null, Position(Column.B, Row.THIRTEEN) to null, Position(Column.C, Row.THIRTEEN) to Black, Position(Column.D, Row.THIRTEEN) to Black, Position(Column.E, Row.THIRTEEN) to null, Position(Column.F, Row.THIRTEEN) to null, Position(Column.G, Row.THIRTEEN) to null, Position(Column.H, Row.THIRTEEN) to null, Position(Column.I, Row.THIRTEEN) to null, Position(Column.J, Row.THIRTEEN) to null, Position(Column.K, Row.THIRTEEN) to null, Position(Column.L, Row.THIRTEEN) to null, Position(Column.M, Row.THIRTEEN) to null, Position(Column.N, Row.THIRTEEN) to null, Position(Column.O, Row.THIRTEEN) to null,
    Position(Column.A, Row.TWELVE) to null, Position(Column.B, Row.TWELVE) to null, Position(Column.C, Row.TWELVE) to Black, Position(Column.D, Row.TWELVE) to null, Position(Column.E, Row.TWELVE) to Black, Position(Column.F, Row.TWELVE) to null, Position(Column.G, Row.TWELVE) to null, Position(Column.H, Row.TWELVE) to null, Position(Column.I, Row.TWELVE) to null, Position(Column.J, Row.TWELVE) to null, Position(Column.K, Row.TWELVE) to null, Position(Column.L, Row.TWELVE) to null, Position(Column.M, Row.TWELVE) to null, Position(Column.N, Row.TWELVE) to null, Position(Column.O, Row.TWELVE) to null,
    Position(Column.A, Row.ELEVEN) to null, Position(Column.B, Row.ELEVEN) to null, Position(Column.C, Row.ELEVEN) to null, Position(Column.D, Row.ELEVEN) to Black, Position(Column.E, Row.ELEVEN) to Black, Position(Column.F, Row.ELEVEN) to null, Position(Column.G, Row.ELEVEN) to null, Position(Column.H, Row.ELEVEN) to null, Position(Column.I, Row.ELEVEN) to null, Position(Column.J, Row.ELEVEN) to null, Position(Column.K, Row.ELEVEN) to null, Position(Column.L, Row.ELEVEN) to null, Position(Column.M, Row.ELEVEN) to null, Position(Column.N, Row.ELEVEN) to null, Position(Column.O, Row.ELEVEN) to null,
    Position(Column.A, Row.TEN) to null, Position(Column.B, Row.TEN) to null, Position(Column.C, Row.TEN) to null, Position(Column.D, Row.TEN) to null, Position(Column.E, Row.TEN) to null, Position(Column.F, Row.TEN) to null, Position(Column.G, Row.TEN) to null, Position(Column.H, Row.TEN) to null, Position(Column.I, Row.TEN) to null, Position(Column.J, Row.TEN) to null, Position(Column.K, Row.TEN) to null, Position(Column.L, Row.TEN) to null, Position(Column.M, Row.TEN) to null, Position(Column.N, Row.TEN) to null, Position(Column.O, Row.TEN) to null,
    Position(Column.A, Row.NINE) to null, Position(Column.B, Row.NINE) to null, Position(Column.C, Row.NINE) to null, Position(Column.D, Row.NINE) to null, Position(Column.E, Row.NINE) to null, Position(Column.F, Row.NINE) to null, Position(Column.G, Row.NINE) to null, Position(Column.H, Row.NINE) to null, Position(Column.I, Row.NINE) to null, Position(Column.J, Row.NINE) to null, Position(Column.K, Row.NINE) to null, Position(Column.L, Row.NINE) to null, Position(Column.M, Row.NINE) to null, Position(Column.N, Row.NINE) to null, Position(Column.O, Row.NINE) to null,
    Position(Column.A, Row.EIGHT) to null, Position(Column.B, Row.EIGHT) to null, Position(Column.C, Row.EIGHT) to null, Position(Column.D, Row.EIGHT) to null, Position(Column.E, Row.EIGHT) to null, Position(Column.F, Row.EIGHT) to null, Position(Column.G, Row.EIGHT) to null, Position(Column.H, Row.EIGHT) to null, Position(Column.I, Row.EIGHT) to null, Position(Column.J, Row.EIGHT) to null, Position(Column.K, Row.EIGHT) to null, Position(Column.L, Row.EIGHT) to null, Position(Column.M, Row.EIGHT) to null, Position(Column.N, Row.EIGHT) to null, Position(Column.O, Row.EIGHT) to null,
    Position(Column.A, Row.SEVEN) to null, Position(Column.B, Row.SEVEN) to null, Position(Column.C, Row.SEVEN) to null, Position(Column.D, Row.SEVEN) to null, Position(Column.E, Row.SEVEN) to null, Position(Column.F, Row.SEVEN) to null, Position(Column.G, Row.SEVEN) to null, Position(Column.H, Row.SEVEN) to null, Position(Column.I, Row.SEVEN) to null, Position(Column.J, Row.SEVEN) to null, Position(Column.K, Row.SEVEN) to null, Position(Column.L, Row.SEVEN) to null, Position(Column.M, Row.SEVEN) to null, Position(Column.N, Row.SEVEN) to null, Position(Column.O, Row.SEVEN) to null,
    Position(Column.A, Row.SIX) to null, Position(Column.B, Row.SIX) to null, Position(Column.C, Row.SIX) to null, Position(Column.D, Row.SIX) to null, Position(Column.E, Row.SIX) to null, Position(Column.F, Row.SIX) to null, Position(Column.G, Row.SIX) to null, Position(Column.H, Row.SIX) to null, Position(Column.I, Row.SIX) to null, Position(Column.J, Row.SIX) to null, Position(Column.K, Row.SIX) to null, Position(Column.L, Row.SIX) to null, Position(Column.M, Row.SIX) to null, Position(Column.N, Row.SIX) to null, Position(Column.O, Row.SIX) to null,
    Position(Column.A, Row.FIVE) to null, Position(Column.B, Row.FIVE) to null, Position(Column.C, Row.FIVE) to null, Position(Column.D, Row.FIVE) to null, Position(Column.E, Row.FIVE) to null, Position(Column.F, Row.FIVE) to null, Position(Column.G, Row.FIVE) to null, Position(Column.H, Row.FIVE) to null, Position(Column.I, Row.FIVE) to null, Position(Column.J, Row.FIVE) to null, Position(Column.K, Row.FIVE) to null, Position(Column.L, Row.FIVE) to null, Position(Column.M, Row.FIVE) to null, Position(Column.N, Row.FIVE) to null, Position(Column.O, Row.FIVE) to null,
    Position(Column.A, Row.FOUR) to null, Position(Column.B, Row.FOUR) to null, Position(Column.C, Row.FOUR) to null, Position(Column.D, Row.FOUR) to null, Position(Column.E, Row.FOUR) to null, Position(Column.F, Row.FOUR) to null, Position(Column.G, Row.FOUR) to null, Position(Column.H, Row.FOUR) to null, Position(Column.I, Row.FOUR) to null, Position(Column.J, Row.FOUR) to null, Position(Column.K, Row.FOUR) to null, Position(Column.L, Row.FOUR) to null, Position(Column.M, Row.FOUR) to null, Position(Column.N, Row.FOUR) to null, Position(Column.O, Row.FOUR) to null,
    Position(Column.A, Row.THREE) to null, Position(Column.B, Row.THREE) to null, Position(Column.C, Row.THREE) to null, Position(Column.D, Row.THREE) to null, Position(Column.E, Row.THREE) to null, Position(Column.F, Row.THREE) to null, Position(Column.G, Row.THREE) to null, Position(Column.H, Row.THREE) to null, Position(Column.I, Row.THREE) to null, Position(Column.J, Row.THREE) to null, Position(Column.K, Row.THREE) to null, Position(Column.L, Row.THREE) to null, Position(Column.M, Row.THREE) to null, Position(Column.N, Row.THREE) to null, Position(Column.O, Row.THREE) to null,
    Position(Column.A, Row.TWO) to null, Position(Column.B, Row.TWO) to null, Position(Column.C, Row.TWO) to null, Position(Column.D, Row.TWO) to null, Position(Column.E, Row.TWO) to null, Position(Column.F, Row.TWO) to null, Position(Column.G, Row.TWO) to null, Position(Column.H, Row.TWO) to null, Position(Column.I, Row.TWO) to null, Position(Column.J, Row.TWO) to null, Position(Column.K, Row.TWO) to null, Position(Column.L, Row.TWO) to null, Position(Column.M, Row.TWO) to null, Position(Column.N, Row.TWO) to null, Position(Column.O, Row.TWO) to null,
    Position(Column.A, Row.ONE) to null, Position(Column.B, Row.ONE) to null, Position(Column.C, Row.ONE) to null, Position(Column.D, Row.ONE) to null, Position(Column.E, Row.ONE) to null, Position(Column.F, Row.ONE) to null, Position(Column.G, Row.ONE) to null, Position(Column.H, Row.ONE) to null, Position(Column.I, Row.ONE) to null, Position(Column.J, Row.ONE) to null, Position(Column.K, Row.ONE) to null, Position(Column.L, Row.ONE) to null, Position(Column.M, Row.ONE) to null, Position(Column.N, Row.ONE) to null, Position(Column.O, Row.ONE) to null
)

val FOUR_FOUR_BOARD: MutableMap<Position, Stone?> = mutableMapOf(
    Position(Column.A, Row.FIFTEEN) to null, Position(Column.B, Row.FIFTEEN) to null, Position(Column.C, Row.FIFTEEN) to Black, Position(Column.D, Row.FIFTEEN) to null, Position(Column.E, Row.FIFTEEN) to null, Position(Column.F, Row.FIFTEEN) to null, Position(Column.G, Row.FIFTEEN) to null, Position(Column.H, Row.FIFTEEN) to null, Position(Column.I, Row.FIFTEEN) to null, Position(Column.J, Row.FIFTEEN) to null, Position(Column.K, Row.FIFTEEN) to null, Position(Column.L, Row.FIFTEEN) to null, Position(Column.M, Row.FIFTEEN) to null, Position(Column.N, Row.FIFTEEN) to null, Position(Column.O, Row.FIFTEEN) to null,
    Position(Column.A, Row.FOURTEEN) to null, Position(Column.B, Row.FOURTEEN) to null, Position(Column.C, Row.FOURTEEN) to Black, Position(Column.D, Row.FOURTEEN) to null, Position(Column.E, Row.FOURTEEN) to null, Position(Column.F, Row.FOURTEEN) to null, Position(Column.G, Row.FOURTEEN) to null, Position(Column.H, Row.FOURTEEN) to null, Position(Column.I, Row.FOURTEEN) to null, Position(Column.J, Row.FOURTEEN) to null, Position(Column.K, Row.FOURTEEN) to null, Position(Column.L, Row.FOURTEEN) to null, Position(Column.M, Row.FOURTEEN) to null, Position(Column.N, Row.FOURTEEN) to null, Position(Column.O, Row.FOURTEEN) to null,
    Position(Column.A, Row.THIRTEEN) to null, Position(Column.B, Row.THIRTEEN) to null, Position(Column.C, Row.THIRTEEN) to null, Position(Column.D, Row.THIRTEEN) to null, Position(Column.E, Row.THIRTEEN) to null, Position(Column.F, Row.THIRTEEN) to null, Position(Column.G, Row.THIRTEEN) to null, Position(Column.H, Row.THIRTEEN) to null, Position(Column.I, Row.THIRTEEN) to null, Position(Column.J, Row.THIRTEEN) to null, Position(Column.K, Row.THIRTEEN) to null, Position(Column.L, Row.THIRTEEN) to null, Position(Column.M, Row.THIRTEEN) to null, Position(Column.N, Row.THIRTEEN) to null, Position(Column.O, Row.THIRTEEN) to null,
    Position(Column.A, Row.TWELVE) to null, Position(Column.B, Row.TWELVE) to null, Position(Column.C, Row.TWELVE) to Black, Position(Column.D, Row.TWELVE) to Black, Position(Column.E, Row.TWELVE) to null, Position(Column.F, Row.TWELVE) to null, Position(Column.G, Row.TWELVE) to Black, Position(Column.H, Row.TWELVE) to null, Position(Column.I, Row.TWELVE) to Black, Position(Column.J, Row.TWELVE) to Black, Position(Column.K, Row.TWELVE) to null, Position(Column.L, Row.TWELVE) to null, Position(Column.M, Row.TWELVE) to null, Position(Column.N, Row.TWELVE) to null, Position(Column.O, Row.TWELVE) to null,
    Position(Column.A, Row.ELEVEN) to null, Position(Column.B, Row.ELEVEN) to null, Position(Column.C, Row.ELEVEN) to Black, Position(Column.D, Row.ELEVEN) to null, Position(Column.E, Row.ELEVEN) to null, Position(Column.F, Row.ELEVEN) to null, Position(Column.G, Row.ELEVEN) to null, Position(Column.H, Row.ELEVEN) to null, Position(Column.I, Row.ELEVEN) to null, Position(Column.J, Row.ELEVEN) to null, Position(Column.K, Row.ELEVEN) to null, Position(Column.L, Row.ELEVEN) to null, Position(Column.M, Row.ELEVEN) to null, Position(Column.N, Row.ELEVEN) to null, Position(Column.O, Row.ELEVEN) to null,
    Position(Column.A, Row.TEN) to null, Position(Column.B, Row.TEN) to null, Position(Column.C, Row.TEN) to Black, Position(Column.D, Row.TEN) to null, Position(Column.E, Row.TEN) to null, Position(Column.F, Row.TEN) to null, Position(Column.G, Row.TEN) to null, Position(Column.H, Row.TEN) to null, Position(Column.I, Row.TEN) to null, Position(Column.J, Row.TEN) to null, Position(Column.K, Row.TEN) to null, Position(Column.L, Row.TEN) to null, Position(Column.M, Row.TEN) to null, Position(Column.N, Row.TEN) to null, Position(Column.O, Row.TEN) to null,
    Position(Column.A, Row.NINE) to null, Position(Column.B, Row.NINE) to null, Position(Column.C, Row.NINE) to null, Position(Column.D, Row.NINE) to null, Position(Column.E, Row.NINE) to null, Position(Column.F, Row.NINE) to null, Position(Column.G, Row.NINE) to null, Position(Column.H, Row.NINE) to White, Position(Column.I, Row.NINE) to null, Position(Column.J, Row.NINE) to Black, Position(Column.K, Row.NINE) to null, Position(Column.L, Row.NINE) to null, Position(Column.M, Row.NINE) to null, Position(Column.N, Row.NINE) to null, Position(Column.O, Row.NINE) to null,
    Position(Column.A, Row.EIGHT) to null, Position(Column.B, Row.EIGHT) to null, Position(Column.C, Row.EIGHT) to null, Position(Column.D, Row.EIGHT) to null, Position(Column.E, Row.EIGHT) to null, Position(Column.F, Row.EIGHT) to null, Position(Column.G, Row.EIGHT) to null, Position(Column.H, Row.EIGHT) to Black, Position(Column.I, Row.EIGHT) to null, Position(Column.J, Row.EIGHT) to Black, Position(Column.K, Row.EIGHT) to Black, Position(Column.L, Row.EIGHT) to null, Position(Column.M, Row.EIGHT) to null, Position(Column.N, Row.EIGHT) to null, Position(Column.O, Row.EIGHT) to null,
    Position(Column.A, Row.SEVEN) to null, Position(Column.B, Row.SEVEN) to null, Position(Column.C, Row.SEVEN) to null, Position(Column.D, Row.SEVEN) to null, Position(Column.E, Row.SEVEN) to null, Position(Column.F, Row.SEVEN) to null, Position(Column.G, Row.SEVEN) to null, Position(Column.H, Row.SEVEN) to Black, Position(Column.I, Row.SEVEN) to null, Position(Column.J, Row.SEVEN) to null, Position(Column.K, Row.SEVEN) to null, Position(Column.L, Row.SEVEN) to null, Position(Column.M, Row.SEVEN) to null, Position(Column.N, Row.SEVEN) to null, Position(Column.O, Row.SEVEN) to null,
    Position(Column.A, Row.SIX) to null, Position(Column.B, Row.SIX) to null, Position(Column.C, Row.SIX) to null, Position(Column.D, Row.SIX) to null, Position(Column.E, Row.SIX) to Black, Position(Column.F, Row.SIX) to null, Position(Column.G, Row.SIX) to null, Position(Column.H, Row.SIX) to Black, Position(Column.I, Row.SIX) to null, Position(Column.J, Row.SIX) to Black, Position(Column.K, Row.SIX) to null, Position(Column.L, Row.SIX) to null, Position(Column.M, Row.SIX) to null, Position(Column.N, Row.SIX) to null, Position(Column.O, Row.SIX) to null,
    Position(Column.A, Row.FIVE) to null, Position(Column.B, Row.FIVE) to null, Position(Column.C, Row.FIVE) to null, Position(Column.D, Row.FIVE) to White, Position(Column.E, Row.FIVE) to Black, Position(Column.F, Row.FIVE) to Black, Position(Column.G, Row.FIVE) to Black, Position(Column.H, Row.FIVE) to null, Position(Column.I, Row.FIVE) to null, Position(Column.J, Row.FIVE) to null, Position(Column.K, Row.FIVE) to null, Position(Column.L, Row.FIVE) to null, Position(Column.M, Row.FIVE) to null, Position(Column.N, Row.FIVE) to null, Position(Column.O, Row.FIVE) to null,
    Position(Column.A, Row.FOUR) to null, Position(Column.B, Row.FOUR) to null, Position(Column.C, Row.FOUR) to null, Position(Column.D, Row.FOUR) to null, Position(Column.E, Row.FOUR) to null, Position(Column.F, Row.FOUR) to null, Position(Column.G, Row.FOUR) to Black, Position(Column.H, Row.FOUR) to null, Position(Column.I, Row.FOUR) to null, Position(Column.J, Row.FOUR) to null, Position(Column.K, Row.FOUR) to null, Position(Column.L, Row.FOUR) to null, Position(Column.M, Row.FOUR) to null, Position(Column.N, Row.FOUR) to null, Position(Column.O, Row.FOUR) to null,
    Position(Column.A, Row.THREE) to null, Position(Column.B, Row.THREE) to null, Position(Column.C, Row.THREE) to null, Position(Column.D, Row.THREE) to null, Position(Column.E, Row.THREE) to null, Position(Column.F, Row.THREE) to null, Position(Column.G, Row.THREE) to null, Position(Column.H, Row.THREE) to null, Position(Column.I, Row.THREE) to null, Position(Column.J, Row.THREE) to null, Position(Column.K, Row.THREE) to null, Position(Column.L, Row.THREE) to null, Position(Column.M, Row.THREE) to null, Position(Column.N, Row.THREE) to null, Position(Column.O, Row.THREE) to null,
    Position(Column.A, Row.TWO) to null, Position(Column.B, Row.TWO) to null, Position(Column.C, Row.TWO) to null, Position(Column.D, Row.TWO) to null, Position(Column.E, Row.TWO) to null, Position(Column.F, Row.TWO) to null, Position(Column.G, Row.TWO) to null, Position(Column.H, Row.TWO) to null, Position(Column.I, Row.TWO) to null, Position(Column.J, Row.TWO) to null, Position(Column.K, Row.TWO) to null, Position(Column.L, Row.TWO) to null, Position(Column.M, Row.TWO) to null, Position(Column.N, Row.TWO) to null, Position(Column.O, Row.TWO) to null,
    Position(Column.A, Row.ONE) to null, Position(Column.B, Row.ONE) to null, Position(Column.C, Row.ONE) to null, Position(Column.D, Row.ONE) to null, Position(Column.E, Row.ONE) to null, Position(Column.F, Row.ONE) to null, Position(Column.G, Row.ONE) to null, Position(Column.H, Row.ONE) to null, Position(Column.I, Row.ONE) to null, Position(Column.J, Row.ONE) to null, Position(Column.K, Row.ONE) to null, Position(Column.L, Row.ONE) to null, Position(Column.M, Row.ONE) to null, Position(Column.N, Row.ONE) to null, Position(Column.O, Row.ONE) to null
)

val FOUR_FOUR_THREE_BOARD: MutableMap<Position, Stone?> = mutableMapOf(
    Position(Column.A, Row.FIFTEEN) to null, Position(Column.B, Row.FIFTEEN) to null, Position(Column.C, Row.FIFTEEN) to Black, Position(Column.D, Row.FIFTEEN) to null, Position(Column.E, Row.FIFTEEN) to null, Position(Column.F, Row.FIFTEEN) to null, Position(Column.G, Row.FIFTEEN) to null, Position(Column.H, Row.FIFTEEN) to null, Position(Column.I, Row.FIFTEEN) to null, Position(Column.J, Row.FIFTEEN) to null, Position(Column.K, Row.FIFTEEN) to null, Position(Column.L, Row.FIFTEEN) to null, Position(Column.M, Row.FIFTEEN) to null, Position(Column.N, Row.FIFTEEN) to null, Position(Column.O, Row.FIFTEEN) to null,
    Position(Column.A, Row.FOURTEEN) to null, Position(Column.B, Row.FOURTEEN) to Black, Position(Column.C, Row.FOURTEEN) to Black, Position(Column.D, Row.FOURTEEN) to null, Position(Column.E, Row.FOURTEEN) to null, Position(Column.F, Row.FOURTEEN) to null, Position(Column.G, Row.FOURTEEN) to null, Position(Column.H, Row.FOURTEEN) to null, Position(Column.I, Row.FOURTEEN) to null, Position(Column.J, Row.FOURTEEN) to null, Position(Column.K, Row.FOURTEEN) to null, Position(Column.L, Row.FOURTEEN) to null, Position(Column.M, Row.FOURTEEN) to null, Position(Column.N, Row.FOURTEEN) to null, Position(Column.O, Row.FOURTEEN) to null,
    Position(Column.A, Row.THIRTEEN) to null, Position(Column.B, Row.THIRTEEN) to null, Position(Column.C, Row.THIRTEEN) to null, Position(Column.D, Row.THIRTEEN) to null, Position(Column.E, Row.THIRTEEN) to null, Position(Column.F, Row.THIRTEEN) to null, Position(Column.G, Row.THIRTEEN) to null, Position(Column.H, Row.THIRTEEN) to null, Position(Column.I, Row.THIRTEEN) to null, Position(Column.J, Row.THIRTEEN) to null, Position(Column.K, Row.THIRTEEN) to null, Position(Column.L, Row.THIRTEEN) to null, Position(Column.M, Row.THIRTEEN) to null, Position(Column.N, Row.THIRTEEN) to null, Position(Column.O, Row.THIRTEEN) to null,
    Position(Column.A, Row.TWELVE) to null, Position(Column.B, Row.TWELVE) to null, Position(Column.C, Row.TWELVE) to Black, Position(Column.D, Row.TWELVE) to Black, Position(Column.E, Row.TWELVE) to null, Position(Column.F, Row.TWELVE) to null, Position(Column.G, Row.TWELVE) to Black, Position(Column.H, Row.TWELVE) to null, Position(Column.I, Row.TWELVE) to Black, Position(Column.J, Row.TWELVE) to Black, Position(Column.K, Row.TWELVE) to null, Position(Column.L, Row.TWELVE) to null, Position(Column.M, Row.TWELVE) to null, Position(Column.N, Row.TWELVE) to null, Position(Column.O, Row.TWELVE) to null,
    Position(Column.A, Row.ELEVEN) to null, Position(Column.B, Row.ELEVEN) to null, Position(Column.C, Row.ELEVEN) to Black, Position(Column.D, Row.ELEVEN) to null, Position(Column.E, Row.ELEVEN) to null, Position(Column.F, Row.ELEVEN) to null, Position(Column.G, Row.ELEVEN) to null, Position(Column.H, Row.ELEVEN) to null, Position(Column.I, Row.ELEVEN) to null, Position(Column.J, Row.ELEVEN) to null, Position(Column.K, Row.ELEVEN) to null, Position(Column.L, Row.ELEVEN) to null, Position(Column.M, Row.ELEVEN) to null, Position(Column.N, Row.ELEVEN) to null, Position(Column.O, Row.ELEVEN) to null,
    Position(Column.A, Row.TEN) to null, Position(Column.B, Row.TEN) to null, Position(Column.C, Row.TEN) to Black, Position(Column.D, Row.TEN) to null, Position(Column.E, Row.TEN) to null, Position(Column.F, Row.TEN) to null, Position(Column.G, Row.TEN) to null, Position(Column.H, Row.TEN) to null, Position(Column.I, Row.TEN) to null, Position(Column.J, Row.TEN) to null, Position(Column.K, Row.TEN) to null, Position(Column.L, Row.TEN) to null, Position(Column.M, Row.TEN) to null, Position(Column.N, Row.TEN) to null, Position(Column.O, Row.TEN) to null,
    Position(Column.A, Row.NINE) to null, Position(Column.B, Row.NINE) to null, Position(Column.C, Row.NINE) to null, Position(Column.D, Row.NINE) to null, Position(Column.E, Row.NINE) to null, Position(Column.F, Row.NINE) to null, Position(Column.G, Row.NINE) to null, Position(Column.H, Row.NINE) to White, Position(Column.I, Row.NINE) to null, Position(Column.J, Row.NINE) to Black, Position(Column.K, Row.NINE) to null, Position(Column.L, Row.NINE) to null, Position(Column.M, Row.NINE) to null, Position(Column.N, Row.NINE) to null, Position(Column.O, Row.NINE) to null,
    Position(Column.A, Row.EIGHT) to null, Position(Column.B, Row.EIGHT) to null, Position(Column.C, Row.EIGHT) to null, Position(Column.D, Row.EIGHT) to null, Position(Column.E, Row.EIGHT) to null, Position(Column.F, Row.EIGHT) to null, Position(Column.G, Row.EIGHT) to null, Position(Column.H, Row.EIGHT) to Black, Position(Column.I, Row.EIGHT) to null, Position(Column.J, Row.EIGHT) to Black, Position(Column.K, Row.EIGHT) to Black, Position(Column.L, Row.EIGHT) to null, Position(Column.M, Row.EIGHT) to null, Position(Column.N, Row.EIGHT) to null, Position(Column.O, Row.EIGHT) to null,
    Position(Column.A, Row.SEVEN) to null, Position(Column.B, Row.SEVEN) to null, Position(Column.C, Row.SEVEN) to null, Position(Column.D, Row.SEVEN) to null, Position(Column.E, Row.SEVEN) to null, Position(Column.F, Row.SEVEN) to null, Position(Column.G, Row.SEVEN) to null, Position(Column.H, Row.SEVEN) to Black, Position(Column.I, Row.SEVEN) to null, Position(Column.J, Row.SEVEN) to null, Position(Column.K, Row.SEVEN) to null, Position(Column.L, Row.SEVEN) to null, Position(Column.M, Row.SEVEN) to null, Position(Column.N, Row.SEVEN) to null, Position(Column.O, Row.SEVEN) to null,
    Position(Column.A, Row.SIX) to null, Position(Column.B, Row.SIX) to null, Position(Column.C, Row.SIX) to null, Position(Column.D, Row.SIX) to null, Position(Column.E, Row.SIX) to Black, Position(Column.F, Row.SIX) to null, Position(Column.G, Row.SIX) to null, Position(Column.H, Row.SIX) to Black, Position(Column.I, Row.SIX) to null, Position(Column.J, Row.SIX) to Black, Position(Column.K, Row.SIX) to null, Position(Column.L, Row.SIX) to null, Position(Column.M, Row.SIX) to null, Position(Column.N, Row.SIX) to null, Position(Column.O, Row.SIX) to null,
    Position(Column.A, Row.FIVE) to null, Position(Column.B, Row.FIVE) to null, Position(Column.C, Row.FIVE) to null, Position(Column.D, Row.FIVE) to White, Position(Column.E, Row.FIVE) to Black, Position(Column.F, Row.FIVE) to Black, Position(Column.G, Row.FIVE) to Black, Position(Column.H, Row.FIVE) to null, Position(Column.I, Row.FIVE) to null, Position(Column.J, Row.FIVE) to null, Position(Column.K, Row.FIVE) to null, Position(Column.L, Row.FIVE) to null, Position(Column.M, Row.FIVE) to null, Position(Column.N, Row.FIVE) to null, Position(Column.O, Row.FIVE) to null,
    Position(Column.A, Row.FOUR) to null, Position(Column.B, Row.FOUR) to null, Position(Column.C, Row.FOUR) to null, Position(Column.D, Row.FOUR) to null, Position(Column.E, Row.FOUR) to null, Position(Column.F, Row.FOUR) to null, Position(Column.G, Row.FOUR) to Black, Position(Column.H, Row.FOUR) to null, Position(Column.I, Row.FOUR) to null, Position(Column.J, Row.FOUR) to null, Position(Column.K, Row.FOUR) to null, Position(Column.L, Row.FOUR) to null, Position(Column.M, Row.FOUR) to null, Position(Column.N, Row.FOUR) to null, Position(Column.O, Row.FOUR) to null,
    Position(Column.A, Row.THREE) to null, Position(Column.B, Row.THREE) to null, Position(Column.C, Row.THREE) to null, Position(Column.D, Row.THREE) to null, Position(Column.E, Row.THREE) to null, Position(Column.F, Row.THREE) to null, Position(Column.G, Row.THREE) to null, Position(Column.H, Row.THREE) to null, Position(Column.I, Row.THREE) to null, Position(Column.J, Row.THREE) to null, Position(Column.K, Row.THREE) to null, Position(Column.L, Row.THREE) to null, Position(Column.M, Row.THREE) to null, Position(Column.N, Row.THREE) to null, Position(Column.O, Row.THREE) to null,
    Position(Column.A, Row.TWO) to null, Position(Column.B, Row.TWO) to null, Position(Column.C, Row.TWO) to null, Position(Column.D, Row.TWO) to null, Position(Column.E, Row.TWO) to null, Position(Column.F, Row.TWO) to null, Position(Column.G, Row.TWO) to null, Position(Column.H, Row.TWO) to null, Position(Column.I, Row.TWO) to null, Position(Column.J, Row.TWO) to null, Position(Column.K, Row.TWO) to null, Position(Column.L, Row.TWO) to null, Position(Column.M, Row.TWO) to null, Position(Column.N, Row.TWO) to null, Position(Column.O, Row.TWO) to null,
    Position(Column.A, Row.ONE) to null, Position(Column.B, Row.ONE) to null, Position(Column.C, Row.ONE) to null, Position(Column.D, Row.ONE) to null, Position(Column.E, Row.ONE) to null, Position(Column.F, Row.ONE) to null, Position(Column.G, Row.ONE) to null, Position(Column.H, Row.ONE) to null, Position(Column.I, Row.ONE) to null, Position(Column.J, Row.ONE) to null, Position(Column.K, Row.ONE) to null, Position(Column.L, Row.ONE) to null, Position(Column.M, Row.ONE) to null, Position(Column.N, Row.ONE) to null, Position(Column.O, Row.ONE) to null
)
